name = "vanguard-scraper"
main = "src/index.ts"
compatibility_date = "2022-05-14"

# Lets you call workers periodically, much like a cron job.
# More details: https://developers.cloudflare.com/workers/platform/cron-triggers
# @default `{crons:[]}`
[triggers]
crons = ["0 12 * * *"]

# [secrets] # npm run add-secret <secret_name>
# API_URL